export const categories = [
  "Motor de popa",
  "Motor de centro",
  "H\u00e9lice",
  "Rabeta",
  "El\u00e9trica",
  "Eletr\u00f4nica",
  "Painel",
  "Dire\u00e7\u00e3o",
  "Ferragens",
  "Carreta",
  "Jet ski",
];

const galleries = {
  motor: [
    "./src/assets/products/outboard-yamaha.jpg",
    "./src/assets/products/outboard-illustration.png",
    "./src/assets/products/steering-wheel.jpg",
  ],
  helice: [
    "./src/assets/products/propeller.jpg",
    "./src/assets/products/steering-wheel.jpg",
    "./src/assets/products/outboard-yamaha.jpg",
  ],
  painel: [
    "./src/assets/products/steering-wheel.jpg",
    "./src/assets/products/outboard-yamaha.jpg",
    "./src/assets/products/bilge-pump.png",
  ],
  bomba: [
    "./src/assets/products/bilge-pump.png",
    "./src/assets/products/propeller.jpg",
    "./src/assets/products/outboard-illustration.png",
  ],
};

export const products = [
  {
    id: "mercury-150-rabeta",
    title: "Rabeta Mercury 150HP",
    category: "Rabeta",
    brand: "Mercury",
    model: "150HP 2T",
    condition: "Usado revisado",
    city: "Santos, SP",
    price: 6800,
    compatibility: "Mercury 135 a 175HP",
    partNumber: "Ref. 1647-9148A",
    logistics: "Retirada em marina ou cota\u00e7\u00e3o de envio",
    tag: "Pronta entrega",
    photoLabel: "Rabeta",
    photo: galleries.motor[0],
    gallery: galleries.motor,
    placeholder: true,
    description: "Para recolocar a lancha na \u00e1gua sem esperar uma pe\u00e7a nova chegar do fornecedor.",
  },
  {
    id: "yamaha-15hp-capota",
    title: "Capota Yamaha 15HP",
    category: "Motor de popa",
    brand: "Yamaha",
    model: "15HP",
    condition: "Usado original",
    city: "Angra dos Reis, RJ",
    price: 950,
    compatibility: "Yamaha 15HP Enduro",
    partNumber: "Ref. 6E7-W0070",
    logistics: "Envio leve por transportadora",
    tag: "Original",
    photoLabel: "Capota",
    photo: galleries.motor[1],
    gallery: galleries.motor,
    placeholder: true,
    description: "Boa para reposi\u00e7\u00e3o est\u00e9tica em motor de trabalho ou pesca que ainda est\u00e1 rodando forte.",
  },
  {
    id: "helice-inox-21",
    title: "H\u00e9lice inox passo 21",
    category: "H\u00e9lice",
    brand: "Solas",
    model: "13 1/4 x 21",
    condition: "Usado bom",
    city: "Florian\u00f3polis, SC",
    price: 1750,
    compatibility: "Motores 90 a 150HP",
    partNumber: "Passo 21",
    logistics: "Aceita envio ap\u00f3s confer\u00eancia",
    tag: "Inox",
    photoLabel: "H\u00e9lice",
    photo: galleries.helice[0],
    gallery: galleries.helice,
    placeholder: true,
    description: "Op\u00e7\u00e3o para testar rendimento sem comprar h\u00e9lice nova antes de acertar o conjunto.",
  },
  {
    id: "painel-chave-bombordo",
    title: "Painel de chaves 6 vias",
    category: "Painel",
    brand: "Seachoice",
    model: "6 vias",
    condition: "Novo sem caixa",
    city: "Guaruj\u00e1, SP",
    price: 420,
    compatibility: "Lanchas e barcos de pesca",
    partNumber: "6 vias universal",
    logistics: "Envio nacional",
    tag: "El\u00e9trica",
    photoLabel: "Painel",
    photo: galleries.painel[0],
    gallery: galleries.painel,
    placeholder: true,
    description: "Para trocar painel cansado e organizar bomba, luz, buzina e acess\u00f3rios no comando.",
  },
  {
    id: "caixa-direcao-cabo",
    title: "Caixa de dire\u00e7\u00e3o com cabo",
    category: "Dire\u00e7\u00e3o",
    brand: "Teleflex",
    model: "12 p\u00e9s",
    condition: "Usado revisado",
    city: "Niter\u00f3i, RJ",
    price: 1350,
    compatibility: "Motores de popa at\u00e9 115HP",
    partNumber: "Cabo 12 p\u00e9s",
    logistics: "Retirada ou envio por volume",
    tag: "Revisado",
    photoLabel: "Dire\u00e7\u00e3o",
    photo: galleries.painel[0],
    gallery: galleries.painel,
    placeholder: true,
    description: "Resolve dire\u00e7\u00e3o pesada em conjunto pequeno sem partir direto para kit novo.",
  },
  {
    id: "guincho-carreta",
    title: "Guincho manual para carreta",
    category: "Carreta",
    brand: "Bepo",
    model: "900kg",
    condition: "Usado bom",
    city: "Itaja\u00ed, SC",
    price: 690,
    compatibility: "Carretas rodovi\u00e1rias pequenas e m\u00e9dias",
    partNumber: "900kg",
    logistics: "Retirada recomendada",
    tag: "Carreta",
    photoLabel: "Guincho",
    photo: galleries.helice[0],
    gallery: galleries.helice,
    placeholder: true,
    description: "Ajuda na subida do barco na rampa e evita improviso na hora de tirar da \u00e1gua.",
  },
  {
    id: "volvo-penta-d3-rabeta",
    title: "Rabeta Volvo Penta D3",
    category: "Rabeta",
    brand: "Volvo Penta",
    model: "D3 190",
    condition: "Usado a revisar",
    city: "Rio de Janeiro, RJ",
    price: 19800,
    compatibility: "Volvo Penta D3 e aplica\u00e7\u00f5es compat\u00edveis",
    partNumber: "D3",
    logistics: "Frete por conta do comprador",
    tag: "Centro rabeta",
    photoLabel: "D3",
    photo: galleries.motor[0],
    gallery: galleries.motor,
    placeholder: true,
    description: "Para oficina que prefere avaliar uma unidade usada antes de importar conjunto novo.",
  },
  {
    id: "modulo-seadoo-215",
    title: "M\u00f3dulo Sea-Doo RXP 215",
    category: "Jet ski",
    brand: "Sea-Doo",
    model: "RXP 215",
    condition: "Usado testado",
    city: "Campinas, SP",
    price: 4200,
    compatibility: "Sea-Doo RXP/RXT 215, anos selecionados",
    partNumber: "420664946",
    logistics: "Envio com embalagem refor\u00e7ada",
    tag: "Jet ski",
    photoLabel: "M\u00f3dulo",
    photo: galleries.motor[1],
    gallery: galleries.motor,
    placeholder: true,
    description: "Item de alto valor em que c\u00f3digo, ano e teste fazem toda diferen\u00e7a na consulta.",
  },
  {
    id: "plotter-garmin-7",
    title: "GPS plotter 7 polegadas",
    category: "Eletr\u00f4nica",
    brand: "Garmin",
    model: "7 polegadas",
    condition: "Usado funcionando",
    city: "Paraty, RJ",
    price: 2400,
    compatibility: "Rede NMEA e instala\u00e7\u00f5es n\u00e1uticas comuns",
    partNumber: "Plotter 7",
    logistics: "Envio leve com seguro",
    tag: "Eletr\u00f4nica",
    photoLabel: "GPS",
    photo: galleries.painel[0],
    gallery: galleries.painel,
    placeholder: true,
    description: "Para substituir equipamento cansado e manter navega\u00e7\u00e3o com investimento controlado.",
  },
  {
    id: "bomba-porao-2000",
    title: "Bomba de por\u00e3o 2000 GPH",
    category: "El\u00e9trica",
    brand: "Rule",
    model: "2000 GPH",
    condition: "Novo de estoque antigo",
    city: "Salvador, BA",
    price: 580,
    compatibility: "Lanchas, veleiros e barcos de pesca",
    partNumber: "2000 GPH",
    logistics: "Envio nacional",
    tag: "Seguran\u00e7a",
    photoLabel: "Bomba",
    photo: galleries.bomba[0],
    gallery: galleries.bomba,
    placeholder: true,
    description: "Pe\u00e7a pequena, cr\u00edtica e f\u00e1cil de enviar quando o cadastro informa vaz\u00e3o e tens\u00e3o.",
  },
];

export function formatPrice(value) {
  return new Intl.NumberFormat("pt-BR", {
    currency: "BRL",
    style: "currency",
    maximumFractionDigits: 0,
  }).format(value);
}